### PR TITLE
Andrewmirsky/ch130/automatically test pull requests

### PR DESCRIPTION
**Pull request by ajmirsky**
Adding travis ci configuration file to auto run tests for pull requests to `master`, `release` and `staging` branches.

### CODE REVIEW

**Comment by ajmirsky** [comment]
@geoffscott when you get a chance, can you enable travis ci on the github repo? it needs admin rights to configure. you can probably also change the `general settings` in travis ci to only test pull requests (i think build push is enabled by default?)

**Comment by geoffscott** [comment]
@ajmirsky Travis is enabled, push turned off

**Comment by geoffscott** [comment]
Hi @ajmirsky, shall I merge this?

**Comment by ajmirsky** [comment]
yup. all good.

**Pull request merged**
